/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.ResultSet;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author msi-a
 */
public class AllResevedRooms extends javax.swing.JFrame 
{

    /**
     * Creates new form AllResevedRooms
     */
    public AllResevedRooms() 
    {
        initComponents();
        DeletBook.setVisible(false);
        DoneRecord.setVisible(false);
        
try {
    Class.forName("com.mysql.jdbc.Driver"); // تحميل درايفر MySQL
    String url = "jdbc:mysql://localhost/hotel_db?useUnicode=true&characterEncoding=UTF-8";
    String user = "root";
    String password = "";

    Connection con = (Connection) DriverManager.getConnection(url, user, password);
    Statement stmt = (Statement) con.createStatement();

    String getAllResevedRooms = "SELECT * FROM add_booking";
    
    ResultSet result = (ResultSet) stmt.executeQuery(getAllResevedRooms);

    while(result.next())
    {
          DefaultTableModel model = (DefaultTableModel) BookTable.getModel();
    
    
    Vector v = new Vector();
    
    
    v.add(result.getString(2));/*لان مصفوفة فتعاملت وياه بقيم الindex اللي بقاعدة البيانات*/
    v.add(result.getString(3)); /*فاعدة البيانات تحسب الid رقم1 فابلش من 2*/
    v.add(result.getString(4));/*نكدر نجيب اسماء مالت قاعدة البيانات بدال الاندكسات كلش عادي*/
    v.add(result.getString(5));
    v.add(result.getString(6));
    model.addRow(v);
    BookTable.repaint();
    }
   
     
    
  

} catch (ClassNotFoundException ex) {
    Logger.getLogger(AllResevedRooms.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null, "خطأ: مكتبة MySQL غير موجودة");
}  catch (SQLException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "حدث خطأ في الاتصال بقاعدة البيانات: " + ex.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SearchButoon = new javax.swing.JButton();
        SearchTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookTable = new javax.swing.JTable();
        DeletBook = new javax.swing.JButton();
        DoneRecord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(177, 158, 124));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("All Reserved Rooms");

        SearchButoon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/images/icons8-search-50.png"))); // NOI18N
        SearchButoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButoonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButoon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchButoon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        BookTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Guest name", "Room_Number", "Duration(from-to)", "Type_booking", "Reservation status"
            }
        ));
        BookTable.setRowHeight(35);
        BookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BookTable);

        DeletBook.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DeletBook.setText("Delete");
        DeletBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletBookMouseClicked(evt);
            }
        });

        DoneRecord.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DoneRecord.setText("Reservation completion");
        DoneRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(DeletBook)
                        .addGap(687, 687, 687))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(DoneRecord)
                        .addGap(611, 611, 611))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(DeletBook)
                .addGap(18, 18, 18)
                .addComponent(DoneRecord)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookTableMouseClicked
    
       
     
        
        
        DeletBook.setVisible(true);
        DoneRecord.setVisible(true);
        
          
  
    }//GEN-LAST:event_BookTableMouseClicked

        
    private void DoneRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneRecordActionPerformed
       
        
        try
{
Class.forName("com.mysql.jdbc.Driver"); /*استدعاء المكتبة بين القوسين*/
String url="jdbc:mysql://localhost/hotel_db"+"?"+"use unicode=true&characterEncoding=UTF-8";
String user= "root";
String password= "";
/*هذا اتصال بقاعدة البيانات*/
Connection con = (Connection) DriverManager.getConnection(url,user,password);

/*هذا واسطة اتصال بين البيانات وقاعدة البيانات*/
Statement Statement= (Statement) con.createStatement();


   /* String Duration_hotelValue = null;
    String Guest_NameValue = null;
    String Room_NumberValue = null;
    String Type_bookingValue = null; */
    int row = BookTable.getSelectedRow();
String GuestName = BookTable.getValueAt(row, 0).toString();
DoneRecord.setVisible(true);/*تطلعلي الزر*/
/*نص الكويري المكتوب مايفهمه الكومبايلر بس قاعدة البيانات تفهمه*/
String done="UPDATE add_booking SET Reservation_status='Completed' WHERE Guest_Name='"+GuestName+"' "; /*للتحديث من المستمر بالحجز للمكتمل*/

Statement.executeUpdate(done);

JOptionPane.showMessageDialog(null, "The booking has ended");
dispose();
new AllResevedRooms().setVisible(true);

/*Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhosst/hotel_db"+"?"+"use unicode = true&charsetEncoding=UTF-8");
اللي بعد اسم قاعدة البيانات تنسيق يدعم اللغة العربية وهاي طريقة ثانية*/

}
catch (ClassNotFoundException ex)
{
Logger.getLogger(NewABookRoom.class.getName()).log(Level.SEVERE, null, ex);






}       catch (SQLException ex) {
            Logger.getLogger(AllResevedRooms.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DoneRecordActionPerformed

    private void DeletBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletBookMouseClicked
             try
{
Class.forName("com.mysql.jdbc.Driver"); 
String url="jdbc:mysql://localhost/hotel_db"+"?"+"use unicode=true&characterEncoding=UTF-8";
String user= "root";
String password= "";
/*هذا اتصال بقاعدة البيانات*/
Connection con = (Connection) DriverManager.getConnection(url,user,password);

/*هذا واسطة اتصال بين البيانات وقاعدة البيانات*/
Statement Statement= (Statement) con.createStatement();

    int p = BookTable.getSelectedRow();
    String g = BookTable.getValueAt(p, 0).toString();/*colom=0*/
        /*بهاي التعليمتين انا جبت مواضع الاسطر مالت التيبل مالتي بحيث يعرضلي او يحسبلي ارقام اماكنهن*/
    System.out.println(g);/*اكدر الغيه بس ضفته للطبع حتى اتاكد من شغلي*/
    DeletBook.setVisible(true);/*تطلعلي الزر*/
    
   String deleteRecord=" DELETE  FROM add_booking WHERE Guest_Name = '"+g+"' ";
    
   Statement.executeUpdate(deleteRecord);

   JOptionPane.showMessageDialog(null, "deleted");
       dispose();
new AllResevedRooms().setVisible(true);


}
catch (ClassNotFoundException ex)
{
Logger.getLogger(NewABookRoom.class.getName()).log(Level.SEVERE, null, ex);






}       catch (SQLException ex) {
            Logger.getLogger(AllResevedRooms.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_DeletBookMouseClicked

    private void SearchButoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButoonActionPerformed
           String searchText = SearchTextField.getText().trim(); /* حتى احصل على النص المدخل بحقل البحث*/
    
    if (searchText.isEmpty()) {
        JOptionPane.showMessageDialog(null, "يرجى إدخال اسم النزيل للبحث.");
        return;
    }
    
    try {
        Class.forName("com.mysql.jdbc.Driver"); 
        String url = "jdbc:mysql://localhost/hotel_db?useUnicode=true&characterEncoding=UTF-8";
        String user = "root";
        String password = "";
        
        Connection con = (Connection) DriverManager.getConnection(url, user, password);
        Statement stmt = (Statement) con.createStatement();
        
       
        String searchQuery = "SELECT * FROM add_booking WHERE Guest_Name LIKE '%" + searchText + "%'";
        ResultSet result = (ResultSet) stmt.executeQuery(searchQuery);
        
        DefaultTableModel model = (DefaultTableModel) BookTable.getModel();
        model.setRowCount(0); /* مسح البيانات السابقة من الجدول*/
        
        boolean hasResults = false;
        while (result.next()) {
            Vector v = new Vector();
            v.add(result.getString(2)); 
            v.add(result.getString(3)); 
            v.add(result.getString(4)); 
            v.add(result.getString(5)); 
            v.add(result.getString(6)); 
            model.addRow(v);
            hasResults = true;
        }
        
        if (!hasResults) {
            JOptionPane.showMessageDialog(null, "لا توجد نتائج تطابق اسم النزيل.");
        }
        
        BookTable.repaint();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(AllResevedRooms.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "خطأ: مكتبة MySQL غير موجودة.");
    } catch (SQLException ex) {
        Logger.getLogger(AllResevedRooms.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "حدث خطأ في الاتصال بقاعدة البيانات: " + ex.getMessage());
    }

    }//GEN-LAST:event_SearchButoonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllResevedRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllResevedRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllResevedRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllResevedRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run()
            {
                new AllResevedRooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BookTable;
    private javax.swing.JButton DeletBook;
    private javax.swing.JButton DoneRecord;
    private javax.swing.JButton SearchButoon;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
