/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author msi-a
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home()
    {
        initComponents();
        
        totalRecords();
        Allresevedrooms();
        BookingOngoing();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        Allavailable = new javax.swing.JLabel();
        AllavailableProgress = new javax.swing.JProgressBar();
        Allresevd = new javax.swing.JLabel();
        AllresevedProgress = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        Allbooking = new javax.swing.JLabel();
        AllbookingProgress = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(177, 158, 124));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Allavailable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Allavailable.setText("All completed Booking");
        jPanel1.add(Allavailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 200, 30));

        AllavailableProgress.setValue(40);
        jPanel1.add(AllavailableProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        Allresevd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Allresevd.setText("All Completed rooms ");
        jPanel1.add(Allresevd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 100, 200, 30));

        AllresevedProgress.setValue(40);
        jPanel1.add(AllresevedProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 140, -1, -1));

        jButton1.setText("Add a booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        jButton2.setText("Update the Page");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/images/OIP (3).jpeg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        jButton5.setText("AllResevedRooms");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, -1, -1));

        Allbooking.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Allbooking.setText("All Booking");
        jPanel1.add(Allbooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 160, 40));

        AllbookingProgress.setValue(40);
        jPanel1.add(AllbookingProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("The completed bookings");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("All Booking");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("The incomplete bookings");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1504, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      new NewABookRoom().setVisible(true);/*يفتحلي لبصفحة*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       new AllResevedRooms().setVisible(true);/*حتى يطلعلي كل الحجوزات بالتيبل مالتي*/
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      dispose();
      new Home().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Allavailable;
    private javax.swing.JProgressBar AllavailableProgress;
    private javax.swing.JLabel Allbooking;
    private javax.swing.JProgressBar AllbookingProgress;
    private javax.swing.JLabel Allresevd;
    private javax.swing.JProgressBar AllresevedProgress;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables

    
    /*احصائية الحجوزات كلها*/
    private void totalRecords() 
    {
        try {
    Class.forName("com.mysql.jdbc.Driver"); // تحميل درايفر MySQL
    String url = "jdbc:mysql://localhost/hotel_db?useUnicode=true&characterEncoding=UTF-8";
    String user = "root";
    String password = "";

    Connection con = (Connection) DriverManager.getConnection(url, user, password);
    Statement stmt = (Statement) con.createStatement();

    String getAllResevedRooms = "SELECT * FROM add_booking";
    
    ResultSet result = (ResultSet) stmt.executeQuery(getAllResevedRooms);
    int totalRecords=0;
    while(result.next())
    {
      totalRecords ++;
      
      Allbooking.setText(""+totalRecords); /*the value of lable وضفنا ال"" لان يريد اي شي يدل ع الtext*/ 
      AllbookingProgress.setValue(totalRecords);/*this is a Progress*/
      
    }
   
     
    
  

} catch (ClassNotFoundException ex) {
    Logger.getLogger(AllResevedRooms.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null, "خطأ: مكتبة MySQL غير موجودة");
}  catch (SQLException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "حدث خطأ في الاتصال بقاعدة البيانات: " + ex.getMessage());
    }
}

    private void Allresevedrooms() 
    {
        
        try {
    Class.forName("com.mysql.jdbc.Driver"); // تحميل درايفر MySQL
    String url = "jdbc:mysql://localhost/hotel_db?useUnicode=true&characterEncoding=UTF-8";
    String user = "root";
    String password = "";

    Connection con = (Connection) DriverManager.getConnection(url, user, password);
    Statement stmt = (Statement) con.createStatement();

    String getAllResevedRooms = "SELECT * FROM add_booking WHERE Reservation_status='Completed'";
    
    ResultSet result = (ResultSet) stmt.executeQuery(getAllResevedRooms);
    int totalRecordsDone=0;
    while(result.next())
    {
      totalRecordsDone ++;
      
      Allavailable.setText(""+totalRecordsDone); /*the value of lable وضفنا ال"" لان يريد اي شي يدل ع الtext*/ 
      AllavailableProgress.setValue(totalRecordsDone);/*this is a Progress*/
      
    }
   
     
    
  

} catch (ClassNotFoundException ex) {
    Logger.getLogger(AllResevedRooms.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null, "خطأ: مكتبة MySQL غير موجودة");
}  catch (SQLException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "حدث خطأ في الاتصال بقاعدة البيانات: " + ex.getMessage());
    }
    }

    private void BookingOngoing()
    {
       
        
             try {
    Class.forName("com.mysql.jdbc.Driver"); // تحميل درايفر MySQL
    String url = "jdbc:mysql://localhost/hotel_db?useUnicode=true&characterEncoding=UTF-8";
    String user = "root";
    String password = "";

    Connection con = (Connection) DriverManager.getConnection(url, user, password);
    Statement stmt = (Statement) con.createStatement();

    String getAllResevedRooms = "SELECT * FROM add_booking WHERE Reservation_status='Booking Ongoing'";
    
    ResultSet result = (ResultSet) stmt.executeQuery(getAllResevedRooms);
    int totalRecordsnotDone=0;
    while(result.next())
    {
      totalRecordsnotDone ++;
      
      Allresevd.setText(""+totalRecordsnotDone); /*the value of lable وضفنا ال"" لان يريد اي شي يدل ع الtext*/ 
      AllresevedProgress.setValue(totalRecordsnotDone);/*this is a Progress*/
      
    }
   
     
    
  

} catch (ClassNotFoundException ex) {
    Logger.getLogger(AllResevedRooms.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null, "خطأ: مكتبة MySQL غير موجودة");
}  catch (SQLException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "حدث خطأ في الاتصال بقاعدة البيانات: " + ex.getMessage());
    }
    
        
    }
}

    

