/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import com.mysql.jdbc.Connection;
/*import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;*/
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.logging.Logger;
import java.util.logging.Level;


/**
 *
 * @author msi-a
 */
public class NewABookRoom extends javax.swing.JFrame {

    /**
     * Creates new form NewABookRoom
     */
    public NewABookRoom()
    {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Room_Number = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Type_booking = new javax.swing.JComboBox();
        Guest_Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Duration_hotel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(177, 158, 124));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add a new booking");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Room Number");

        Type_booking.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Type_booking.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single room", "Private Suite", "" }));

        Guest_Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Guest Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Duration of stay in the hotel");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/images/icons8-correct-100 (1).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Type of booking");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(Type_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(538, 538, 538))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(478, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Room_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Guest_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Duration_hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(487, 487, 487))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(703, 703, 703))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(596, 596, 596)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guest_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Room_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Duration_hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(Type_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(!Guest_Name.equals(""))
       {/*Guest_Name	Room_Number	Duration_hotel	Type_bookingهاي اسماء جداول قاعدة البيانات الداخل الphpmyadmin*/
           String Guest_NameValue= Guest_Name.getText();
           String Room_NumberValue= Room_Number.getText();
           String Duration_hotelValue= Duration_hotel.getText();
           String Type_bookingValue= Type_booking.getSelectedItem().toString();
           /*بهاي الخطوات انا مغيرة قيمة العناصر الداخل الدزاين وهنا استدعيتهن حتى ادزهن لقاعدة البيانات*/
           
           /*JOptionPane.showMessageDialog(null, Type_bookingValue);
           هاي التعليمة تطلعلي شنو اختارينا من نوع للحجز*/
           
           
       
           try {
               insertData(Guest_NameValue, Room_NumberValue, Duration_hotelValue, Type_bookingValue);
           } catch (SQLException ex) {
               Logger.getLogger(NewABookRoom.class.getName()).log(Level.SEVERE, null, ex);
           }
         new Home().setVisible(true);
       }
       
    }//GEN-LAST:event_jButton1ActionPerformed
public static void insertData(String Guest_Name, String Room_Number,String Duration_hotel,String Type_booking) throws SQLException
{
try
{
Class.forName("com.mysql.jdbc.Driver"); 
String url="jdbc:mysql://localhost/hotel_db"+"?"+"use unicode=true&characterEncoding=UTF-8";
String user= "root";
String password= "";
/*هذا اتصال بقاعدة البيانات*/
Connection con = (Connection) DriverManager.getConnection(url,user,password);

/*هذا واسطة اتصال بين البيانات وقاعدة البيانات*/
Statement Statement= (Statement) con.createStatement();


   /* String Duration_hotelValue = null;
    String Guest_NameValue = null;
    String Room_NumberValue = null;
    String Type_bookingValue = null; */
    


String insertData= "INSERT INTO add_booking (Guest_Name,Room_Number,Duration_hotel,Type_booking,Reservation_status)VALUES('"+Guest_Name+"','"+Room_Number+"','"+Duration_hotel+"','"+Type_booking+"','Booking Ongoing')";

Statement.executeUpdate(insertData);

JOptionPane.showMessageDialog(null, "تم اضافة البيانات بنجاح");

/*ذني الشرطين بس حتى اتاكد من الاتصال*/
if(con.equals(""))
{
    System.out.print("Not Connection");
}
else
{
    System.out.print(" Connection Ok");
}

/*Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhosst/hotel_db"+"?"+"use unicode = true&charsetEncoding=UTF-8");
اللي بعد اسم قاعدة البيانات تنسيق يدعم اللغة العربية وهاي طريقة ثانية*/

}
catch (ClassNotFoundException ex)
{
Logger.getLogger(NewABookRoom.class.getName()).log(Level.SEVERE, null, ex);
/*Logger.getLogger(NewABookRoom.class.getName()):

هذا الجزء يجيب لك سجل (Logger) خاص بالكلاس اللي احنا بيه (هنا الكلاس اسمه NewABookRoom). يعني هالشي يربط الخطأ بالكود اللي صار بيه.
log(Level.SEVERE, null, ex):

Level.SEVERE يعني هالخطأ خطير، يعني من الدرجة العالية.
null معناها ما نكتب أي رسالة إضافية.
ex هو الخطأ نفسه اللي طلع.
شلون نحجيها بصراوي؟
"يعني يابه هاذا يخزن الخطأ اللي صار بالكلاس مالنا، ويخليها بدرجة خطورة عالية (SEVERE) حتى يبين انه المشكلة مو بسيطة. وبهاي الطريقة نقدر نعرف شنو اللي صار ونعالجه بعدين."






*/
}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewABookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewABookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewABookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewABookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewABookRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Duration_hotel;
    private javax.swing.JTextField Guest_Name;
    private javax.swing.JTextField Room_Number;
    private javax.swing.JComboBox Type_booking;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
