---
services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-kde
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC  #change time zone user timdedatectl
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    volumes:
      - /docker/webtop-kde:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3001:3000
      #- 3001:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
    

   
