services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '380:80'
      - '81:81'
      - '441:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      

      #login
      # Email:    admin@example.com
      #Password: changeme